/* DDNet++ tiles */
#ifndef GAME_MAPITEMS_DDPP_H
#define GAME_MAPITEMS_DDPP_H

#include <engine/shared/protocol.h>

// entities
// their internal index is shifted
// so the user facing index that will be shown in the
// editor game layer can be seen in the comments
enum
{
	ENTITY_WEAPON_GUN = 50, // 241
	ENTITY_WEAPON_HAMMER = 51, // 242
	ENTITY_PLANT = 52, // 243
};

// tiles
enum
{
	TILE_MONEY_PLUS = 114,
	TILE_MONEY_DOUBLE = 115,

	TILE_BANK = 119,
	TILE_JAIL = 121,
	TILE_JAILRELEASE = 122,
	TILE_BALANCE_BATTLE_1 = 123,
	TILE_BALANCE_BATTLE_2 = 124,
	TILE_FNG_SCORE = 130,
	TILE_BLOCK_TOURNA_SPAWN = 131,
	TILE_PVP_ARENA_SPAWN = 132,

	TILE_BLOCKWAVE_HUMAN = 134,
	TILE_BLOCKWAVE_BOT = 135,

	TILE_RAINBOW = 145,
	TILE_ATOM = 146,
	TILE_TRAIL = 147,

	TILE_VANILLA_MODE = 152,
	TILE_DDRACE_MODE = 153,

	TILE_BLOODY = 154,

	TILE_MONEY = 160,
	TILE_SHOP = 161,
	TILE_ROOM = 162,
	TILE_DDPP_END = 163,
	TILE_MONEY_POLICE = 164,

	TILE_KING_OF_THE_HILL = 169,

	// block deathmatch spawns
	TILE_BLOCK_DM_A1 = 165, //arena 1
	TILE_BLOCK_DM_A2 = 166, //arena 2
	TILE_BLOCK_DM_JOIN = 167, //join block dm mode

	TILE_VIP_PLUS_ONLY = 172,

	TILE_SURVIVAL_LOBBY = 177,
	TILE_SURVIVAL_SPAWN = 178,
	TILE_SURVIVAL_DEATHMATCH = 179,

	TILE_SPREAD_GUN = 180,

	// botspawns planned for survival and singleplayer levels
	TILE_BOTSPAWN_1 = 181,
	TILE_BOTSPAWN_2 = 182,
	TILE_BOTSPAWN_3 = 183,
	TILE_BOTSPAWN_4 = 184,

	// drops the ctf flags
	TILE_FLAG_STOP = 185,

	TILE_NO_HAMMER = 186,
	TILE_CAPTCHA_SPAWN = 187,
	TILE_CAPTCHA_VERIFY = 188,

	TILE_CONFIG_1 = 182,
	TILE_CONFIG_2 = 183,

	TILE_HEART_GUN = 244,
	TILE_SHOP_SPAWN = 255,

	TILE_END_CUSTOM = 255, // all new tiles on top of this line

	// F-DDrace
	NUM_INDICES = 256,
};

// THESE ARE NOT ACTUAL TILE INDICES
enum
{
	CFG_TILE_OFF = 0,
	CFG_TILE_FREEZE = 1,
	CFG_TILE_UNFREEZE = 2,
	CFG_TILE_DEEP = 3,
	CFG_TILE_UNDEEP = 4,
	CFG_TILE_HOOK = 5,
	CFG_TILE_UNHOOK = 6,
	CFG_TILE_DEATH = 7,
	CFG_TILE_GIVE_BLOODY = 8,
	CFG_TILE_GIVE_RAINBOW = 9,
	CFG_TILE_GIVE_SPREADGUN = 10,
};

#endif
