#!/bin/bash
# Run this script to generate a config for a random map change.
# Make sure to adjust the variables MAPSDIR and CFG to your needs.
#
# MAPSDIR - directory to your maps folder absoulte or relative
# CFG - path to the teeworlds config created also relative or absoulte
#
# Then start a teewolrds server and add this vote:
# add_vote "random map" exec rand_map.cfg

MAPSDIR=maps
CFG=rand_map.cfg

if [ ! -d $MAPSDIR ]
then
    echo "Error: maps dir not found '$MAPSDIR'."
    exit 1
fi

while true
do
    max=`ls $MAPSDIR/*.map | wc -l`
    rand=`awk "BEGIN{srand();print int(rand()*($max)) + 1}"`
    map=`ls $MAPSDIR/*.map | head -n $rand | tail -n 1`

    echo "max: $max rand: $rand"
    echo "map: $map"
    echo "# generated by rand_map.sh script" > $CFG
    echo "# https://github.com/DDNetPP/DDNetPP/blob/master/ddpp_scripts/rand_map.sh" >> $CFG
    echo "echo random map=$map" >> $CFG
    echo "sv_map \"$(basename $map .map)\"" >> $CFG
    sleep 5
done

