name: Check Rust

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      CARGO_HTTP_MULTIPLEXING: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    - name: Run Rustdoc
      run: |
        RUSTDOCFLAGS=-Dwarnings DDNET_TEST_NO_LINK=1 cargo doc

  cxxbridge:
    runs-on: ubuntu-latest
    env:
      CARGO_HTTP_MULTIPLEXING: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
           workspaces: |
               src/mastersrv
               src/masterping
               ./
    - name: Run cxxbridge
      run: |
        cargo install cxxbridge-cmd@1.0.71
        python scripts/generate_rust_bridge.py
        git diff --exit-code
